# file: nginx/tasks/main.yml

- include: package.yml
  when: nginx_install_method == "package"
- include: source.yml
  when: nginx_install_method == "source"
- include: scripts.yml
- include: configure.yml
- include: default_site.yml
- include: sites.yml
  when: nginx_sites is defined and nginx_sites and nginx_sites|lower != 'none'
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
